CREATE TABLE IF NOT EXISTS jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  company VARCHAR(120) NOT NULL,
  location VARCHAR(120) NOT NULL,
  category VARCHAR(80) NOT NULL,
  job_type ENUM('Full-time', 'Part-time', 'Contract', 'Internship', 'Remote') NOT NULL DEFAULT 'Full-time',
  experience_level ENUM('Entry Level', 'Mid Level', 'Senior Level', 'Lead') NOT NULL DEFAULT 'Mid Level',
  salary_min INT NULL,
  salary_max INT NULL,
  description TEXT NOT NULL,
  requirements TEXT NOT NULL,
  apply_url VARCHAR(255) NULL,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_jobs_search (title, company, location, category),
  INDEX idx_jobs_filters (location, category, job_type, experience_level),
  INDEX idx_jobs_featured (is_featured, created_at)
);
